name: Testes da API

on:
  push:
    branches: [ main, testes-automatizados ]
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    env:
      ADMIN_EMAIL: admin@escola.com
      ADMIN_SENHA: admin123

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test